# Generated by Django 2.2.6 on 2019-10-24 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.Discount')),
                ('ingridients', models.ManyToManyField(blank=True, null=True, to='dishes.Ingredient')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.Size')),
            ],
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
