# Generated by Django 2.2.6 on 2019-10-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20191024_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name_plural': 'AD'},
        ),
    ]
