# Generated by Django 2.2.6 on 2019-10-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20191031_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name_plural': 'Dishes'},
        ),
    ]
