# Generated by Django 2.2.6 on 2019-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_auto_20191031_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='ingridients',
            field=models.ManyToManyField(to='dishes.Ingredient'),
        ),
    ]
