# Generated by Django 2.2.6 on 2019-10-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0004_auto_20191031_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('place_delivery', models.CharField(max_length=250)),
                ('user_profile', models.CharField(max_length=250)),
                ('dishes', models.ManyToManyField(blank=True, null=True, to='dishes.Dishes')),
                ('drinks', models.ManyToManyField(blank=True, null=True, to='dishes.Drink')),
            ],
        ),
    ]
