# Generated by Django 2.2.6 on 2019-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(to='dishes.Dishes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='drinks',
            field=models.ManyToManyField(to='dishes.Drink'),
        ),
    ]
